title: Mohammed Farhan | Cybersecurity Blog
author: Mohammed Farhan
email: mohammedfarhan.kn@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  A Cybersecurity Professional and Developer who builds and breaks things. Checkout my blog and writeups for more information
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Mohammed Farhan
  tagline: Developer. Cybersecurity Consultant
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  showPicker: false

 # generate social links in footer
  social_links:
    twitter: farhankn
    github:  farhankn
    linkedIn: in/farhankn
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
